"""empty message

Revision ID: 5a47b380450d
Revises: b5ce816e5b0a
Create Date: 2021-11-26 04:49:37.965158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a47b380450d'
down_revision = 'b5ce816e5b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BookReview', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('BookReview', sa.Column('rating', sa.Integer(), nullable=False))
    op.drop_column('BookReview', 'comment_date')
    op.drop_column('BookReview', 'star')
    op.alter_column('book', 'publication_date',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'publication_date',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('BookReview', sa.Column('star', sa.INTEGER(), nullable=False))
    op.add_column('BookReview', sa.Column('comment_date', sa.DATETIME(), nullable=False))
    op.drop_column('BookReview', 'rating')
    op.drop_column('BookReview', 'created_at')
    # ### end Alembic commands ###
